### PR TITLE
Fix: should have returned BatchRun for bitrise step

### PR DESCRIPTION
**Pull request by mwakizaka**
- No update required on magic-pod-api-client users since this does not affect magic-pod-api-client behaviour.
- Maybe it is necessary to make a tag for bitrise step though.

### CODE REVIEW

**Comment by nkns165** [comment]
Sorry, I just don't understand in detail about recent changes (ex. public API response change).  These are just my question, rather than there are some problems.

- This PR's contents seem different from those of https://github.com/Magic-Pod/bitrise-step-magic-pod/pull/2/files.  Are you going to replace the change with this PR's contents?
- In old implementation, I think logic for waiting results was implemented in `common.go` so that we don't have to care especially about Bitrise step.  Is this also correct after this change?

If yes, please proceed to merge.

**Comment by mwakizaka** [comment]
Sorry, maybe the explanation wasn't enough.

> This PR's contents seem different from those of https://github.com/Magic-Pod/bitrise-step-magic-pod/pull/2/files. Are you going to replace the change with this PR's contents?

Yes

> I think logic for waiting results was implemented in common.go so that we don't have to care especially about Bitrise step. Is this also correct after this change?

Yes

I would like to recover a backward compatibility which was mistakenly broken by https://github.com/Magic-Pod/magic-pod-api-client/commit/aeba3b04020551b6432bbe7725d2580d0c94503e. 

The return value of `ExecuteBatchRun` is used by https://github.com/Magic-Pod/bitrise-step-magic-pod/blob/c972f4e9e8513b90b5a840dbf2ec610bcc680096/main.go#L157
I'm not sure how `MAGIC_POD_TEST_RESULT` environment variable in bitrise step is referred in bitrise though. I appreciate if you could explain.

**Comment by nkns165** [comment]
Thank you for your explanation!

> I'm not sure how MAGIC_POD_TEST_RESULT environment variable in bitrise step is referred in bitrise though. I appreciate if you could explain.

OK.  It was just a boolean value before cross batch runs are introduced.  When `magicpod-ui-test` was deprecated and `magic-pod` step was released, it became the current format.
On Bitrise we can select whether we stop the build when a step failed or not.  https://devcenter.bitrise.io/tips-and-tricks/dont-mark-build-failed-if-step-fails/  If users configure this step as "skippable", they can use the results programmatically in following steps.

Detail results are output while execution, but results that can be parsed easily (not free text) are more helpful for power users.  I think magic-pod-api-client itself could have similar feature in the future.

**Review by nkns165 — APPROVED** [review]

**Comment by mwakizaka** [comment]
Thanks!

**Pull request merged**
